// Interface automatically generated by schemas-to-ts

export interface Blog {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    Title: string;
    locale: string;
    localizations?: { data: Blog[] };
  };
}
export interface Blog_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  locale: string;
  localizations?: Blog_Plain[];
}

export interface Blog_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  locale: string;
  localizations?: Blog[];
}

export interface Blog_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  locale: string;
  localizations?: Blog[];
}
