// Interface automatically generated by schemas-to-ts

export interface Review {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    Title: string;
    locale: string;
    localizations?: { data: Review[] };
  };
}
export interface Review_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  locale: string;
  localizations?: Review_Plain[];
}

export interface Review_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  locale: string;
  localizations?: Review[];
}

export interface Review_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  locale: string;
  localizations?: Review[];
}
